# Generated by Django 4.2 on 2023-08-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomm", "0002_alter_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rewards",
            field=models.IntegerField(null=True),
        ),
    ]
