# Generated by Django 4.2 on 2023-06-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomm", "0002_alter_product_tags_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Candy", "Candy"),
                    ("Chocolate", "Chocolate"),
                    ("Gift box", "Gift box"),
                    ("Chocolate bar", "Chocolate bar"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
