# Generated by Django 4.2 on 2023-08-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomm", "0004_alter_order_order_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="note",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
